version: '3.8'

services:
  # Node.js service
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: npm start
    volumes:
      - .:/app
    ports:
      - "3000:3000"

  # Nginx service
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    depends_on:
      - node-app
    volumes:
      - ./build:/usr/share/nginx/html
