version: '3.8'

services:
  app:
    image: node:18.15.0
    working_dir: /app
    command: >
      sh -c "npm install && ls -al && npm run build && nginx -g 'daemon off;'"
    volumes:
      - .:/app

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./build:/usr/share/nginx/html
